[package]
name = "gen"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = { workspace = true }
inquire = { version = "*", features = ["editor"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
convert_case = { workspace = true }
rust_search = { workspace = true }
regex = { workspace = true }
git2 = { workspace = true }
lazy_static = "1.4.0"
loading = "0.3.0"
fs_extra = "1.3.0"
indexmap = "2.1.0"
